// Generated by Outstatic - do not edit manually

import type { En, EnFields } from './en'
import type { Zh, ZhFields } from './zh'

export type CollectionName = 'en' | 'zh'

export type SingletonName = never

export interface Collections {
  'en': En
  'zh': Zh
}

export interface Singletons {
}

export type CollectionDocument<C extends CollectionName> = Collections[C]
export type SingletonDocument<S extends SingletonName> = Singletons[S]

/** Union of all document field types for use with load() */
export type AllDocuments = EnFields | ZhFields
