// Generated by Outstatic - do not edit manually
import type { OstDocument } from 'outstatic'

export interface EnFields {
  image?: string
}

export interface En extends OstDocument<EnFields> {}

export type EnField = keyof En
