// Generated by Outstatic - do not edit manually
import type { OstDocument } from 'outstatic'

export interface ZhFields {
  image?: string
}

export interface Zh extends OstDocument<ZhFields> {}

export type ZhField = keyof Zh
